name: CI

on: [push]

jobs:
  package-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.12"
            toxenv: py312
          - python-version: "3.13"
            toxenv: py313

    steps:
      - name: Checkout Project Package
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Test
        run: uv run --frozen tox -e ${{ matrix.toxenv }}

  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout Project Package
      uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Install Dependencies
      run: uv sync --frozen

    - name: Test
      run: uv run --frozen pytest tests/ --cov=src/ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - name: Checkout Project Package
      uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Install Python Dependencies
      run: uv sync --frozen

    - name: Ruff Lint
      run: uv run --frozen ruff check src/ tests/

    - name: Ruff Format
      run: uv run --frozen ruff format --check src/ tests/
